language: node_js
node_js:
- 6
env:
  global:
  - GH_REF: github.com/vaeum/react-material-icon-svg.git
before_install:
- npm config set depth 0
- npm install -g babel-cli
before_script:
script:
  git submodule init
  git submodule update
branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
before_deploy:
- make prepublish
- ls
deploy:
  provider: npm
  email: vaeum@yahoo.com
  skip_cleanup: true
  api_key:
    secure: G8CIhgRPHs3Bjf9lmAbt6LzmM7f0j0Dp6z2r9d4L8sPTLAytDBRxYRHktdffxMcFZIS+/OaHUjzZQL/DAdkAihoq+YxHMBC0JhB7MMPwlui0Ugz+pyeYGMxTGPfQ8c4SZO/hniXoe1Uz+8mldrPnxkFhR0o36C/K+kWB9sRoquNUuS9KONqcRWPAOHMGzS/Hy2pd3EIN4VCjmg6g3TUnHGHrZ7IB1TQliJFhCTBLSxVAcY4RoidirAZ6ZkKcPh/fAIKl4cnjvz9oorH2PPofcrn4xWRO7+UX16WU6wvnV5AaTl/WtX8bMjjVVKoNhGVov1A64WN31cznQzuWVbpZd7fVjGr16AvFRV4vb/7T156Lp9lEVxNVcZVrD6OPYXeY3tmQ67kg32mZV9fXDdgyfdY5SwdCdIoFd9i5O/kJ4qu36dlN7gg2oh0TuT/Q+RrXfKck3iJGVQB1R6Hg8e1T0R2cqadefYY2ZcUfU6UhNk+OEpTwtWVVl8alYFbtOQA6Y8GgNrku21xrAhmf4aC6OqQ379HMpn/vOy9jucr65e1v646wUzVD78TrxejoD2TU99VcwLnc8+4uOGo1dOY6gA59CMCpO85ssP3Ce26kvW4N7GbzAm1U07K3CsQkt+UaisWIH7g16h612VuQXROXqnFEmqhu4/tmpjBmAExPaYw=
  on:
    repo: vaeum/react-material-icon-svg
    branch: master
