language: node_js
node_js:
- 6
env:
  global:
  - GH_REF: github.com/vaeum/react-material-icon-svg.git
before_install:
- npm config set depth 0
# - npm install -g babel-cli
before_script:
script:
- git submodule init
- git submodule update
branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
before_deploy:
- make build
- ls
deploy:
  provider: npm
  email: vaeum@yahoo.com
  skip_cleanup: true
  api_key:
    secure: MwPDoVXUBF+Oo/ViyLnAhyBFT9U4ZV/rbUAJKBk6BaXHTFvuzkMB4rGC9LMu5g2MnxdyYCoc5/Ccj3lTqZFr+xUqOP1QVI9UAPOUg5vMpfaZJqTAvFRNiFKphItdug26Kwfm8SzU4CpAgpNc2bGH2YXADbLe4KBmhIS7cEVNniWkdrYJ8JVMGFXUBi/FaQYafaPYfVWgEe+QEG4j/7wOx7D7YQRdTUowNijGb4fdv2z4efd9WsWnZSYsNcCJHzakBDXp4fil3fVxO1KGRZxEkEHpZL7A5uR1jp4AxRTR6uzS6+lkkxssJ2GNH7RWPmqaEVBbDDI/sjGSvFwRyUBtpysaOs0taJLfZYi7hUqAl7axJaMX6oUQ4hsocHSMO7PZzftNHcjaYOPG9p7u4RLhvXQTas8NIBVHHKMS3zXMckK3ffcHQEa5Bb9DiEsZqBFZwDda+51L7HxB/9uftF2at1SCF+XxghgGvpq8fj06ZbuUGgDlprf5SOnG3MfLIjT+vgs0zKtDo0EL5mZMvFbVrDFP5GVGJRe2K/IKTQXESOf4XAUM7PhfVggdKHrE8YRSq2l9kH5sG16/TMVeuJk0MkT+F5l+KpCCmpZVmUGGgWeGk/3EgSJPHkjkb8cmJgrCyb7I0o915bUloHNoeWEwRMeOLQLmqRV0Pe7xWLXOSGI=
  on:
    repo: vaeum/react-material-icon-svg
    branch: master
